# Generated by Django 4.2.1 on 2024-06-24 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('v_id', models.CharField(default='', max_length=32, null=True)),
                ('registration', models.BooleanField(default=False)),
                ('voting_object', models.BinaryField(default=None, null=True)),
                ('result', models.BinaryField(default=None, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('voting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='votings.voting')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mediator', models.BooleanField(default=False)),
                ('msg1_em', models.URLField(default=None, max_length=1024, null=True)),
                ('s_m_l_h_e_eaek_b', models.URLField(default=None, max_length=1024, null=True)),
                ('msg3_em', models.URLField(default=None, max_length=1024, null=True)),
                ('s_m_msg4_ma', models.URLField(default=None, max_length=1024, null=True)),
                ('mediator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('voting', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='votings.voting')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('counter', models.IntegerField(default=0)),
                ('voting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votings.voting')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('voting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='votings.voting')),
            ],
        ),
    ]
