# Generated by Django 4.2.1 on 2024-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='e_emek_e_eaek_b',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='rfp',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
