# Generated by Django 4.2.1 on 2024-06-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0002_participant_e_emek_e_eaek_b_participant_rfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='msg1_em',
        ),
    ]
