# Generated by Django 4.2.1 on 2024-07-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0003_remove_participant_msg1_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='s_m_l_h_e_eaek_b',
            new_name='s_m_l_h_e_emek_e_eaek_b',
        ),
    ]
