# Generated by Django 4.2.1 on 2024-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0004_rename_s_m_l_h_e_eaek_b_participant_s_m_l_h_e_emek_e_eaek_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='s_m_l_h_e_emek_e_eaek_b',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
