# Generated by Django 4.2.1 on 2024-07-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0006_remove_participant_msg3_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='s_m_l_rfp_and_l_e_eaek_b',
            new_name='msg_ma',
        ),
    ]
