# Generated by Django 4.2.1 on 2024-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0009_rename_s_m_l_h_e_emek_e_eaek_b_participant_msg_mw'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
